Repository arenadotio/pgx, pull requests merged in 2020-04, with the labels that each got.

#60 Convert tests to alcotest and limit ppx_jane to ppx_sexp_conv.
  pgx.opam
  pgx/src/dune
  pgx/src/error_response.ml
  pgx/test/dune
  pgx/test/test_error_response.ml
  pgx/test/test_pgx_value.ml
  pgx_async.opam
  pgx_async/src/dune
  pgx_async/test/dune
  pgx_async/test/test_pgx_async.ml
  pgx_async/test/test_pgx_async_conversions.ml
  pgx_lwt.opam
  pgx_lwt/src/dune
  pgx_lwt/test/dune
  pgx_lwt/test/test_pgx_lwt.ml
  pgx_test/src/dune
  pgx_test/src/pgx_test.ml
  pgx_test/src/pgx_test.mli
  pgx_unix.opam
  pgx_unix/src/dune
  pgx_unix/test/dune
  pgx_unix/test/test_pgx_unix.ml
Labels: size/XL

#63 Update to Alcotest 1.0
  pgx.opam
  pgx_async.opam
  pgx_async/test/test_pgx_async.ml
  pgx_lwt.opam
  pgx_lwt/test/test_pgx_lwt.ml
  pgx_test/src/pgx_test.ml
  pgx_test/src/pgx_test.mli
  pgx_unix.opam
  pgx_unix/test/test_pgx_unix.ml
Labels: size/M

#65 updates for bisect 2
  .circleci/config.yml
  Makefile
  pgx.opam
  pgx/src/dune
  pgx_async.opam
  pgx_async/src/dune
  pgx_lwt.opam
  pgx_lwt/src/dune
  pgx_unix.opam
  pgx_unix/src/dune
Labels: size/M

#62 changes needed for v0.13 janestreet packages
  .circleci/config.yml
  Makefile
  pgx.opam
  pgx/src/io_intf.ml
  pgx/src/pgx.ml
  pgx_async.opam
  pgx_async/bin/pgx_async_example.ml
  pgx_async/test/dune
  pgx_lwt.opam
  pgx_test/src/pgx_test.ml
  pgx_unix.opam
Labels: size/M

#66 Use ocamlformat
  .ocamlformat
  .pre-commit-config.yaml
  dune-project
  pgx/src/access.ml
  pgx/src/access.mli
  pgx/src/dune
  pgx/src/error_response.ml
  pgx/src/error_response.mli
  pgx/src/io_intf.ml
  pgx/src/isolation.ml
  pgx/src/pgx.ml
  pgx/src/pgx.mli
  pgx/src/pgx_aux.ml
  pgx/src/pgx_aux.mli
  pgx/src/pgx_intf.ml
  pgx/src/pgx_value.ml
  pgx/src/pgx_value.mli
  pgx/src/pgx_value_intf.ml
  pgx/src/result_desc.ml
  pgx/src/result_desc.mli
  pgx/src/row_desc.ml
  pgx/src/types.ml
  pgx/test/dune
  pgx/test/test_error_response.ml
  pgx/test/test_pgx_value.ml
  pgx_async/bin/dune
  pgx_async/bin/pgx_async_example.ml
  pgx_async/src/dune
  pgx_async/src/pgx_async.ml
  pgx_async/src/pgx_async.mli
  pgx_async/src/pgx_async_test.ml
  pgx_async/src/pgx_async_test.mli
  pgx_async/test/dune
  pgx_async/test/test_pgx_async.ml
  pgx_async/test/test_pgx_async_conversions.ml
  pgx_lwt/src/dune
  pgx_lwt/src/pgx_lwt.ml
  pgx_lwt/src/pgx_lwt.mli
  pgx_lwt/test/dune
  pgx_lwt/test/test_pgx_lwt.ml
  pgx_test/src/dune
  pgx_test/src/pgx_test.ml
  pgx_test/src/pgx_test.mli
  pgx_unix/src/dune
  pgx_unix/src/pgx_unix.ml
  pgx_unix/src/pgx_unix.mli
  pgx_unix/test/dune
  pgx_unix/test/test_pgx_unix.ml
  pkg/pkg.ml
Labels: size/XXL

#68 Use the new form of `bisect-ppx-report --send-to Coveralls`
  Makefile
Labels: size/XS

#70 we don't use ppx_jane anymore
  pgx_async.opam
  pgx_async/bin/dune
  pgx_async/bin/pgx_async_example.ml
Labels: size/XS

#72 update dune files for conditionally using bisect
  .circleci/config.yml
  Makefile
  pgx/src/dune
  pgx_async/src/dune
  pgx_lwt/src/dune
  pgx_unix/src/dune
Labels: size/M

#76 Make Pgx_async only depend on Async_kernel and Asynx_unix
  pgx_async.opam
  pgx_async/bin/dune
  pgx_async/bin/pgx_async_example.ml
  pgx_async/src/dune
  pgx_async/src/pgx_async.ml
  pgx_async/src/pgx_async.mli
  pgx_async/src/pgx_async_test.ml
  pgx_async/src/pgx_async_test.mli
Labels: size/M

#77 use dune to generate opam files
  dune-project
  pgx.descr
  pgx.opam
  pgx/src/pgx.ml
  pgx/test/dune
  pgx_async.descr
  pgx_async.opam
  pgx_lwt.descr
  pgx_lwt.opam
  pgx_lwt/test/dune
  pgx_test/src/pgx_test.ml
  pgx_unix.descr
  pgx_unix.opam
  pgx_unix/test/dune
  pgx_value_core.descr
  pgx_value_core.opam
  pkg/pkg.ml
Labels: size/L
