Repository arenadotio/pgx, pull requests merged in 2020-05, with the labels that each got.

#79 Add doc url
  dune-project
  pgx.opam
  pgx_async.opam
  pgx_lwt.opam
  pgx_lwt_mirage.opam
  pgx_lwt_unix.opam
  pgx_unix.opam
  pgx_value_core.opam
Labels: size/XS

#82 Add changelog for Pgx v0.2
  CHANGES.md
Labels: size/M

#83 Pgx binary value
  dune-project
  pgx.opam
  pgx/src/dune
  pgx/src/pgx.ml
  pgx/src/pgx_value.ml
  pgx/src/pgx_value.mli
  pgx/src/pgx_value_intf.ml
  pgx/test/test_pgx_value.ml
  pgx_test/src/pgx_test.ml
Labels: size/L

#84 Opam fixes
  .circleci/config.yml
  dune-project
  pgx.opam
  pin_dev.sh
Labels: size/S

#87 Update CHANGES
  CHANGES.md
Labels: size/XS

#88 Add opam descriptions. These fields seem to be required.
  dune-project
  pgx_async.opam
  pgx_lwt.opam
  pgx_lwt_mirage.opam
  pgx_lwt_unix.opam
  pgx_unix.opam
  pgx_value_core.opam
Labels: size/S

#90 Add (package) stanzas to tests
  pgx/test/dune
  pgx_async/test/dune
  pgx_lwt_unix/test/dune
  pgx_unix/test/dune
  pgx_value_core/test/dune
Labels: size/XS

#92 README updates
  README.md
Labels: size/XS

#93 Duplicate test deps for each project
  dune-project
  pgx_unix.opam
  pgx_value_core.opam
Labels: size/S

#94 Add base64 to with-tests
  dune-project
  pgx.opam
  pgx_async.opam
  pgx_lwt.opam
  pgx_lwt_unix.opam
  pgx_unix.opam
Labels: size/S

#96 CI improvements
  .circleci/config.yml
  Makefile
Labels: size/M

#95 adapt to API changes of mirage-conduit (dns resolver now has a timeout)
  .circleci/config.yml
  Makefile
  dune-project
  pgx_lwt_mirage.opam
  pgx_lwt_mirage/src/dune
  pgx_lwt_mirage/src/pgx_lwt_mirage.ml
  pgx_lwt_mirage/src/pgx_lwt_mirage.mli
  unikernel/config.ml
  unikernel/unikernel.ml
Labels: size/M
